parameters:
    memcached.const.opt_compression: -1001
    memcached.const.opt_compression_type: -1004
    memcached.const.opt_prefix_key: -1002
    memcached.const.opt_serializer: -1003
    memcached.const.have_igbinary: 0
    memcached.const.have_json: 0
    memcached.const.have_session: 1
    memcached.const.have_sasl: 0
    memcached.const.opt_client_mode: 37
    memcached.const.opt_dynamic_polling_interval_secs: 38
    memcached.const.opt_hash: 2
    memcached.const.hash_default: 0
    memcached.const.hash_md5: 1
    memcached.const.hash_crc: 2
    memcached.const.hash_fnv1_64: 3
    memcached.const.hash_fnv1a_64: 4
    memcached.const.hash_fnv1_32: 5
    memcached.const.hash_fnv1a_32: 6
    memcached.const.hash_hsieh: 7
    memcached.const.hash_murmur: 8
    memcached.const.opt_distribution: 9
    memcached.const.distribution_modula: 0
    memcached.const.distribution_consistent: 1
    memcached.const.distribution_virtual_bucket: 6
    memcached.const.opt_libketama_compatible: 16
    memcached.const.opt_libketama_hash: 17
    memcached.const.opt_tcp_keepalive: 32
    memcached.const.opt_buffer_writes: 10
    memcached.const.opt_binary_protocol: 18
    memcached.const.opt_no_block: 0
    memcached.const.opt_tcp_nodelay: 1
    memcached.const.opt_socket_send_size: 4
    memcached.const.opt_socket_recv_size: 5
    memcached.const.opt_connect_timeout: 14
    memcached.const.opt_retry_timeout: 15
    memcached.const.opt_send_timeout: 19
    memcached.const.opt_recv_timeout: 20
    memcached.const.opt_poll_timeout: 8
    memcached.const.opt_cache_lookups: 6
    memcached.const.opt_server_failure_limit: 21
    memcached.const.opt_auto_eject_hosts: 28
    memcached.const.opt_hash_with_prefix_key: 25
    memcached.const.opt_noreply: 26
    memcached.const.opt_sort_hosts: 12
    memcached.const.opt_verify_key: 13
    memcached.const.opt_use_udp: 27
    memcached.const.opt_number_of_replicas: 29
    memcached.const.opt_randomize_replica_read: 30
    memcached.const.opt_remove_failed_servers: 35
    memcached.const.res_success: 0
    memcached.const.res_failure: 1
    memcached.const.res_host_lookup_failure: 2
    memcached.const.res_unknown_read_failure: 7
    memcached.const.res_protocol_error: 8
    memcached.const.res_client_error: 9
    memcached.const.res_server_error: 10
    memcached.const.res_write_failure: 5
    memcached.const.res_data_exists: 12
    memcached.const.res_notstored: 14
    memcached.const.res_notfound: 16
    memcached.const.res_partial_read: 18
    memcached.const.res_some_errors: 19
    memcached.const.res_no_servers: 20
    memcached.const.res_end: 21
    memcached.const.res_errno: 26
    memcached.const.res_buffered: 32
    memcached.const.res_timeout: 31
    memcached.const.res_bad_key_provided: 33
    memcached.const.res_stored: 15
    memcached.const.res_deleted: 22
    memcached.const.res_stat: 24
    memcached.const.res_item: 25
    memcached.const.res_not_supported: 28
    memcached.const.res_fetch_notfinished: 30
    memcached.const.res_server_marked_dead: 35
    memcached.const.res_unknown_stat_key: 36
    memcached.const.res_invalid_host_protocol: 34
    memcached.const.res_memory_allocation_failure: 17
    memcached.const.res_memcached_no_config_server: 49
    memcached.const.res_connection_socket_create_failure: 11
    memcached.const.res_payload_failure: -1001
    memcached.const.static_client_mode: 0
    memcached.const.dynamic_client_mode: 1
    memcached.const.serializer_php: 1
    memcached.const.serializer_igbinary: 2
    memcached.const.serializer_json: 3
    memcached.const.serializer_json_array: 4
    memcached.const.compression_fastlz: 2
    memcached.const.compression_zlib: 1
    memcached.const.get_preserve_order: 1
    memcached.enabled: true
    memcached.options: []
    memcached.servers: []
