language: php
php:
  - "5.6"
  - "5.5"
  - "5.4"
  - "5.3"

env:
  - SYMFONY_VERSION=2.1.*
  - SYMFONY_VERSION=2.2.*
  - SYMFONY_VERSION=2.3.*
  - SYMFONY_VERSION=2.4.*
  - SYMFONY_VERSION=2.5.*
  - SYMFONY_VERSION=2.6.*

matrix:
  fast_finish: true

services:
    - redis-server
    - memcached

before_script:
    - ./.travis.cache.sh
    - composer self-update
    - composer require symfony/symfony:${SYMFONY_VERSION} --no-update
    - composer install --dev --prefer-source --no-interaction

