parameters:
    aequasi_cache.apc.class: Doctrine\Common\Cache\ApcCache
    aequasi_cache.array.class: Doctrine\Common\Cache\ArrayCache
    aequasi_cache.file_system.class: Doctrine\Common\Cache\FilesystemCache
    aequasi_cache.memcache.class: Doctrine\Common\Cache\MemcacheCache
    aequasi_cache.memcached.class: Doctrine\Common\Cache\MemcachedCache
    aequasi_cache.redis.class: Doctrine\Common\Cache\RedisCache
    aequasi_cache.php_file.class: Doctrine\Common\Cache\PhpFileCache
    aequasi_cache.win_cache.class: Doctrine\Common\Cache\WinCacheCache
    aequasi_cache.xcache.class: Doctrine\Common\Cache\XcacheCache
    aequasi_cache.zend_data.class: Doctrine\Common\Cache\ZendDataCache
    aequasi_cache.session.handler.class: Aequasi\Bundle\Cache\Session\SessionHandler

services:
    aequasi_cache.apc:
        class: %aequasi_cache.apc.class%
        abstract: true
    aequasi_cache.array:
        class: %aequasi_cache.array.class%
        abstract: true
    aequasi_cache.file_system:
        class: %aequasi_cache.file_system.class%
        abstract: true
    aequasi_cache.memcache:
        class: %aequasi_cache.memcache.class%
        abstract: true
    aequasi_cache.memcached:
        class: %aequasi_cache.memcached.class%
        abstract: true
    aequasi_cache.redis:
        class: %aequasi_cache.redis.class%
        abstract: true
    aequasi_cache.php_file:
        class: %aequasi_cache.php_file.class%
        abstract: true
    aequasi_cache.win_cache:
        class: %aequasi_cache.win_cache.class%
        abstract: true
    aequasi_cache.xcache:
        class: %aequasi_cache.xcache.class%
        abstract: true
    aequasi_cache.zend_data:
        class: %aequasi_cache.zend_data.class%
        abstract: true